version: '3'

services:

  dynamodb:
    image: lambda-websocket-template/dynamodb
    container_name: lambda-websocket-template-dynamodb
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - lambda-websocket-template-dynamodb-store:/home/dynamodblocal/data
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    networks:
      - lambda-local

  dynamodb-admin:
    container_name: lambda-websocket-template-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - lambda-local

  awscli:
    image: lambda-websocket-template/awscli
    container_name: lambda-websocket-template-awscli
    build:
      context: ./awscli
      dockerfile: Dockerfile
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    volumes:
      - ../:/aws
    working_dir: /aws
    depends_on:
      - dynamodb
    networks: 
      - lambda-local

volumes:
  lambda-websocket-template-dynamodb-store:

networks:
  lambda-local:
    external: true